### ISSUE TITLE
Authentication?

### ISSUE THREAD

**Issue by andefred** [Eldsal/eldsal#5]
Should we use Auth0 or roll our own?

**Comment by andefred** [comment]
Where should we store the stripe token

**Comment by andefred** [comment]
Here's a good guide on how to setup Auth0. https://auth0.com/docs/quickstart/spa/react

This was a bit tricky to understand so let me know if you have any problems with this.

**Comment by TimGremalm** [comment]
I've not used Auth0 before. I seems like an easy way to get started! Go for it.

**Comment by andefred** [comment]
We've implemented Auth0 now
